require 'httmultiparty'

require 'phaxio/version'
require 'phaxio/errors'
require 'phaxio/client'
require 'phaxio/status'
require 'phaxio/recipient'
require 'phaxio/recipient_mapper'
require 'phaxio/response'
require 'phaxio/response_mapper'
